#!/usr/bin/env python3
"""Derive each rule's maturity tier from the evidence ledger.

Authoritative for what ships on by default. Three tiers:

  experimental  no measurement. Off by default, never gates CI.
  measured      per-rule precision on a real sample, two adjudicators.
                On by default, advisory.
  confirmed     measured, plus recall pairs and a physical counter delta.
                May gate CI.

Two rules make this a ratchet rather than a table someone edits:

  Tier is computed here, never written in the ledger. A rule cannot declare
  itself mature.

  Evidence carries the hash of the rule's source. Change the rule and the
  evidence is stale, so the tier falls to experimental until re-measured.
  Precision measured against semantics that no longer exist is not evidence
  about the shipping rule, and treating it as such is how a ratchet rots.

    rule_tier.py [--check] [--emit-header <path>]
"""
import argparse
import hashlib
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LEDGER = ROOT / "evidence" / "rules.yaml"

MIN_N = 30
MIN_PRECISION = 0.60
MIN_ADJUDICATORS = 2
MIN_RECALL_PAIRS = 5


def rule_source(rule_id):
    hits = sorted((ROOT / "src" / "rules").glob(f"{rule_id}_*.cpp"))
    return hits[0] if hits else None


def source_sha(rule_id):
    """Hash of the rule's implementation. Reduce-phase rules have no file of
    their own; they are pinned to the pipeline that computes them."""
    p = rule_source(rule_id)
    if p is None:
        p = ROOT / "src" / "core" / "DiagnosticInteraction.cpp"
    if not p.exists():
        return None
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def load_ledger():
    """Deliberately a small hand parser rather than a PyYAML dependency: the
    ledger is machine-written and the build must not need pip."""
    text = LEDGER.read_text()
    rules, cur = {}, None
    in_rules = False
    for raw in text.splitlines():
        if raw.startswith("rules:"):
            in_rules = True
            continue
        if not in_rules or not raw.strip() or raw.strip().startswith("#"):
            continue
        m = re.match(r"^  (FL\d+):\s*(\{\})?\s*$", raw)
        if m:
            cur = m.group(1)
            rules[cur] = {}
            continue
        if cur and raw.startswith("    "):
            km = re.match(r"^    (\w+):\s*(.*)$", raw)
            if km:
                key, val = km.group(1), km.group(2).strip()
                if val.startswith("{"):
                    body = val.strip("{}")
                    d = {}
                    for part in re.findall(r"(\w+):\s*(\[[^\]]*\]|[^,]+)", body):
                        k, v = part[0], part[1].strip()
                        if v.startswith("["):
                            d[k] = [x.strip() for x in v.strip("[]").split(",")
                                    if x.strip()]
                        else:
                            try:
                                d[k] = int(v)
                            except ValueError:
                                d[k] = v
                    rules[cur][key] = d
                elif val and not val.startswith(">"):
                    rules[cur][key] = val
    return rules


def tier_of(rule_id, ev):
    """Returns (tier, reason). Reason is shown to operators, so it says what
    is missing rather than only that something is."""
    prec = ev.get("precision") or {}
    n = prec.get("n", 0)
    adj = len(prec.get("adjudicators", []) or [])
    tp = prec.get("tp", 0) + prec.get("tp_nwf", 0)

    recorded = ev.get("source_sha")
    actual = source_sha(rule_id)
    if recorded and actual and recorded != actual:
        return "experimental", "evidence is stale: the rule changed since it was measured"

    if n == 0:
        return "experimental", "never measured"
    if n < MIN_N:
        return "experimental", f"sample too small (n={n}, need {MIN_N})"
    if adj < MIN_ADJUDICATORS:
        return "experimental", f"{adj} adjudicator(s), need {MIN_ADJUDICATORS}"
    p = tp / n if n else 0.0
    if p < MIN_PRECISION:
        return "experimental", f"precision {p:.2f} below {MIN_PRECISION:.2f}"

    if (ev.get("recall_pairs", 0) or 0) < MIN_RECALL_PAIRS:
        return "measured", f"precision {p:.2f} (n={n}); recall not established"
    if not (ev.get("physical") or {}).get("confirmed"):
        return "measured", f"precision {p:.2f} (n={n}); no physical confirmation"
    return "confirmed", f"precision {p:.2f} (n={n}), recall and counters confirmed"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the ledger is malformed")
    ap.add_argument("--emit-header")
    args = ap.parse_args()

    rules = load_ledger()
    tiers = {rid: tier_of(rid, ev) for rid, ev in sorted(rules.items())}

    if args.emit_header:
        out = ["// Generated by tools/rule_tier.py. Do not edit.",
               "// Tier is derived from evidence/rules.yaml, never declared.",
               "#pragma once", "#include <string_view>", "namespace lshaz {",
               "struct RuleTierEntry { std::string_view id, tier, reason; };",
               "inline constexpr RuleTierEntry kRuleTiers[] = {"]
        for rid, (tier, reason) in tiers.items():
            out.append(f'    {{"{rid}", "{tier}", "{reason}"}},')
        out += ["};", "} // namespace lshaz", ""]
        pathlib.Path(args.emit_header).write_text("\n".join(out))

    on = [r for r, (t, _) in tiers.items() if t != "experimental"]
    for rid, (tier, reason) in tiers.items():
        print(f"{rid:8} {tier:13} {reason}")
    print(f"\ndefault-on: {len(on)} of {len(tiers)} "
          f"({', '.join(on) if on else 'none'})")
    if not on:
        print("no rule has evidence to be on by default; this is the honest "
              "state, not a bug")
    return 0 if rules else 1


if __name__ == "__main__":
    sys.exit(main())
